version: '3'

services:
  aggro:
    image: registry.jan.systems/aggro:latest
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/db.json:/app/db.json
      - ${PWD}/.env:/app/.env
      - ${PWD}/Aggrofile:/app/Aggrofile
